Add component layout photo
MakeYourPet/hexapod pull request #6
Opened 2022-11-05 22:19 UTC by VanGoghComplex

2022-11-05 22:32 UTC, MakeYourPet requested changes
Looks very nice and helpful. Can you just add something in the pic that says it is made by you. And add a disclaimer about the parts. Check the wiring diagram picture.

2022-11-06 13:58 UTC, VanGoghComplex commented
@MakeYourPet , I've updated the image with credit and a parts list. Is this what you were looking for?

2022-11-07 07:48 UTC, MakeYourPet approved these changes

2022-11-07 07:48 UTC, merged

2022-11-07 07:53 UTC, MakeYourPet commented
Merged in. I meant like a part disclaimer that you are not affiliated with any of the parts, but now don't know if it is necessary.